"""create tables

Revision ID: 5d7e62474617
Revises: 
Create Date: 2026-08-13 11:51:15.483575
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d7e62474617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

